### ISSUE TITLE
Can you clarify the license

### ISSUE THREAD

**Issue by dddejan** [smartbugs/smartbugs-wild#3]
I see that you've added a license to the repo. Sorry to nitpick, I just want to make sure that nobody gets in trouble by mistake.

It could be that I am mistaken (not a lawyer), but the contracts in this repo were scraped from Etherscan and it is not clear that they can be relicensed as Apache. Etherscan has recently started allowing deployers to also attach a license. See https://etherscan.io/contract-license-types.

If you could clarify the licensing, this would be very useful.

**Comment by ruimaranhao** [comment]
Thanks, @dddejan. We are looking into this issue.

**Comment by ruimaranhao** [comment]
@dddejan can you check how we addressed it, after discussing with legal.

**Comment by dddejan** [comment]
This is much better, thanks!
