### ISSUE TITLE
How were duplicates found out?

### ISSUE THREAD

**Issue by abhinandanudupa** [smartbugs/smartbugs-wild#6]
Hello!
I an interested in a large scale analysis as you have done. Can you tell me about the tools or scripts that you have used to figure out if the source code is a duplicate of some other contract?

**Comment by tdurieux** [comment]
Hello @abhinandanudupa,

I do not find the code that I used to do that but if I correctly remember I remove all spaces (and maybe comments) from the solidity file and then use md5 hash algo to identify duplicates.

**Comment by abhinandanudupa** [comment]
It's alright, I am also using a similar strategy but I don't remove the spaces and the comments. The strategy has resulted in a reduction of approximately 75%. Maybe I should also try removing the comments and spaces.

Thank you!
